
--
-- Base de données : `primary`
-- Ces tables et leurs données doivent exister avant l'installation de l'application

-- --------------------------------------------------------


--
-- Structure de la table `region`
--

CREATE TABLE `region` (
  `id` int(11) NOT NULL,
  `nom_court_fr` varchar(255) NOT NULL,
  `nom_court_en` varchar(255) NOT NULL,
  `libelle_region_fr` varchar(255) NOT NULL,
  `libelle_region_en` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;


--
-- Index pour la table `region`
--
ALTER TABLE `region`
  ADD PRIMARY KEY (`id`);
--
-- AUTO_INCREMENT pour la table `region`
--
ALTER TABLE `region`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=11;

--
-- Déchargement des données de la table `region`
--

INSERT INTO `region` (`id`, `nom_court_fr`, `nom_court_en`, `libelle_region_fr`, `libelle_region_en`) VALUES
(1, 'ADAMAOUA', 'ADAMAWA', 'DELEGATION Regionale de l\'ADAMAOUA', 'ADAMAWA Regional Delegation'),
(2, 'CENTRE', 'CENTER', 'DELEGATION Regionale du CENTRE', 'CENTER Regional Delegation'),
(3, 'EST', 'EAST', 'DELEGATION Regionale de l\'EST', 'EAST Regional Delegation'),
(4, 'EXTREME-NORD', 'FAR NORTH', 'DELEGATION Regionale de l\'EXTREME-NORD', 'FAR NORTH Regional DELEGATION'),
(5, 'LITTORAL', 'LITTORAL', 'DELEGATION Regionale du LITTORAL', 'LITTORAL Regional Delegation'),
(6, 'NORD', 'NORTH', 'DELEGATION Regionale du NORD', 'NORTH Regional Delegation'),
(7, 'NORD-OUEST', 'NORD-WEST', 'DELEGATION Regionale du NORD-OUEST', 'NORTH-WEST Regional Delegation'),
(8, 'OUEST', 'WEST', 'DELEGATION Regionale de l\'OUEST', 'WEST Regional Delegation'),
(9, 'SUD', 'SOUTH', 'DELEGATION Regionale du SUD', 'SOUTH Regional Delegation'),
(10, 'SUD-OUEST', 'SOUTH-WEST', 'DELEGATION Regionale DU SUD-OUEST', 'SOUTH-WEST Regional Delegation');





--
-- Structure de la table `departement`
--

CREATE TABLE `departement` (
  `id` int(11) NOT NULL,
  `nom_court_fr` varchar(255) NOT NULL,
  `nom_court_en` varchar(255) NOT NULL,
  `libelle_departement_fr` varchar(255) NOT NULL,
  `libelle_departement_en` varchar(255) NOT NULL,
  `id_region` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;


--
-- Index pour la table `departement`
--
ALTER TABLE `departement`
  ADD PRIMARY KEY (`id`),
  ADD KEY `id_region` (`id_region`);
--
-- AUTO_INCREMENT pour la table `departement`
--
ALTER TABLE `departement`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=59;
ALTER TABLE `departement`
  ADD CONSTRAINT `departement_ibfk_1` FOREIGN KEY (`id_region`) REFERENCES `region` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
COMMIT;







--
-- Déchargement des données de la table `departement`
--

INSERT INTO `departement` (`id`, `nom_court_fr`, `nom_court_en`, `libelle_departement_fr`, `libelle_departement_en`, `id_region`) VALUES
(1, 'DJEREM', 'DJEREM', 'DELEGATION DEPARTEMENTALE DU DJEREM', 'DJEREM DIVISIONAL DELEGATION', 1),
(2, 'FARO-ET-DEO', 'FARO-AND-DEO', 'DELEGATION DEPARTEMENTALE DU FARO-ET-DEO', 'FARO-AND-DEO DIVISIONAL DELEGATION', 1),
(3, 'MAYO-BANYO', 'MAYO-BANYO', 'DELEGATION DEPARTEMENTALE DU MAYO-BANYO', 'MAYO-BANYO DIVISIONAL DELEGATION', 1),
(4, 'MBERE', 'MBERE', 'DELEGATION DEPARTEMENTALE DE LA MBERE', 'MBERE DIVISIONAL DELEGATION', 1),
(5, 'VINA', 'VINA', 'DELEGATION DEPARTEMENTALE DE LA VINA', 'VINA DIVISIONAL DELEGATION', 1),
(6, 'HAUTE-SANAGA', 'HAUTE-SANAGA', 'DELEGATION DEPARTEMENTALE DE LA HAUTE-SANAGA', 'HAUTE-SANAGA DIVISIONAL DELEGATION', 2),
(7, 'LEKIE', 'LEKIE', 'DELEGATION DEPARTEMENTALE DE LA LEKIE', 'LEKIE DIVISIONAL DELEGATION', 2),
(8, 'MBAM-ET-INOUBOU', 'MBAM-AND-INOUBOU', 'DELEGATION DEPARTEMENTALE DU MBAM-ET-INOUBOU', 'MBAM-AND-INOUBOU DIVISIONAL DELEGATION', 2),
(9, 'MBAM-ET-KIM', 'MBAM-AND-KIM', 'DELEGATION DEPARTEMENTALE DU MBAM-ET-KIM', 'MBAM-AND-KIM DIVISIONAL DELEGATION', 2),
(10, 'MEFOU-ET-AFAMBA', 'MEFOU-AND-AFAMBA', 'DELEGATION DEPARTEMENTALE DE LA MEFOU-ET-AFAMBA', 'MEFOU-AND-AFAMBA DIVISIONAL DELEGATION', 2),
(11, 'MEFOU-ET-AKONO', 'MEFOU-AND-AKONO', 'DELEGATION DEPARTEMENTALE DE LA MEFOU-ET-AKONO', 'MEFOU-AND-AKONO DIVISIONAL DELEGATION', 2),
(12, 'MFOUNDI', 'MFOUNDI', 'DELEGATION DEPARTEMENTALE DU MFOUNDI', 'MFOUNDI DIVISIONAL DELEGATION', 2),
(13, 'NYONG-ET-KELLE', 'NYONG-ET-KELLE', 'DELEGATION DEPARTEMENTALE DU NYONG-ET-KELLE', 'NYONG-ET-KELLE DIVISIONAL DELEGATION', 2),
(14, 'NYONG-ET-MFOUMOU', 'NYONG-ET-MFOUMOU', 'DELEGATION DEPARTEMENTALE DU NYONG-ET-MFOUMOU', 'NYONG-ET-MFOUMOU DIVISIONAL DELEGATION', 2),
(15, 'NYONG-ET-SO\'O', 'NYONG-ET-SO\'O', 'DELEGATION DEPARTEMENTALE DU NYONG-ET-SO\'O', 'NYONG-ET-SO\'O DIVISIONAL DELEGATION', 2),
(16, 'BOUMBA-ET-NGOKO', 'BOUMBA-AND-NGOKO', 'DELEGATION DEPARTEMENTALE DE LA BOUMBA-ET-NGOKO', 'BOUMBA-AND-NGOKO DIVISIONAL DELEGATION', 3),
(17, 'HAUT-NYONG', 'HAUT-NYONG', 'DELEGATION DEPARTEMENTALE DU HAUT-NYONG', 'HAUT-NYONG DIVISIONAL DELEGATION', 3),
(18, 'KADEY', 'KADEY', 'DELEGATION DEPARTEMENTALE DE LA KADEY', 'KADEY DIVISIONAL DELEGATION', 3),
(19, 'LOM-ET-DJEREM', 'LOM-AND-DJEREM', 'DELEGATION DEPARTEMENTALE DU LOM-ET-DJEREM', 'LOM-AND-DJEREM DIVISIONAL DELEGATION', 3),
(20, 'DIAMARE', 'DIAMARE', 'DELEGATION DEPARTEMENTALE DU DIAMARE', 'DIAMARE DIVISIONAL DELEGATION', 4),
(21, 'LOGONE-ET-CHARI', 'LOGONE-AND-CHARI', 'DELEGATION DEPARTEMENTALE DU LOGONE-ET-CHARI', 'LOGONE-AND-CHARI DIVISIONAL DELEGATION', 4),
(22, 'MAYO-DANAY', 'MAYO-DANAY', 'DELEGATION DEPARTEMENTALE DU MAYO-DANAY', 'MAYO-DANAY DIVISIONAL DELEGATION', 4),
(23, 'MAYO-KANI', 'MAYO-KANI', 'DELEGATION DEPARTEMENTALE DU MAYO-KANI', 'MAYO-KANI DIVISIONAL DELEGATION', 4),
(24, 'MAYO-SAVA', 'MAYO-SAVA', 'DELEGATION DEPARTEMENTALE DU MAYO-SAVA', 'MAYO-SAVA DIVISIONAL DELEGATION', 4),
(25, 'MAYO-TSANAGA', 'MAYO-TSANAGA', 'DELEGATION DEPARTEMENTALE DU MAYO-TSANAGA', 'MAYO-TSANAGA DIVISIONAL DELEGATION', 4),
(26, 'MOUNGO', 'MOUNGO', 'DELEGATION DEPARTEMENTALE DU MOUNGO', 'MOUNGO DIVISIONAL DELEGATION', 5),
(27, 'NKAM', 'NKAM', 'DELEGATION DEPARTEMENTALE DU NKAM', 'NKAM DIVISIONAL DELEGATION', 5),
(28, 'SANAGA-MARITIME', 'SANAGA-MARITIME', 'DELEGATION DEPARTEMENTALE DE LA SANAGA-MARITIME', 'SANAGA-MARITIME DIVISIONAL DELEGATION', 5),
(29, 'WOURI', 'WOURI', 'DELEGATION DEPARTEMENTALE DU WOURI', 'WOURI DIVISIONAL DELEGATION', 5),
(30, 'BENOUE', 'BENOUE', 'DELEGATION DEPARTEMENTALE DE LA BENOUE', 'BENOUE DIVISIONAL DELEGATION', 6),
(31, 'FARO', 'FARO', 'DELEGATION DEPARTEMENTALE DU FARO', 'FARO DIVISIONAL DELEGATION', 6),
(32, 'MAYO-LOUTI', 'MAYO-LOUTI', 'DELEGATION DEPARTEMENTALE DU MAYO-LOUTI', 'MAYO-LOUTI DIVISIONAL DELEGATION', 6),
(33, 'MAYO-REY', 'MAYO-REY', 'DELEGATION DEPARTEMENTALE DU MAYO-REY', 'MAYO-REY DIVISIONAL DELEGATION', 6),
(34, 'BOYO', 'BOYO', 'DELEGATION DEPARTEMENTALE DE LA BOYO', 'BOYO DIVISIONAL DELEGATION', 7),
(35, 'BUI', 'BUI', 'DELEGATION DEPARTEMENTALE DU BUI', 'BUI DIVISIONAL DELEGATION', 7),
(36, 'DONGA-MANTUNG', 'DONGA-MANTUNG', 'DELEGATION DEPARTEMENTALE DU DONGA-MANTUNG', 'DONGA-MANTUNG DIVISIONAL DELEGATION', 7),
(37, 'MENCHUM', 'MENCHUM', 'DELEGATION DEPARTEMENTALE DE LA MENCHUM', 'MENCHUM DIVISIONAL DELEGATION', 7),
(38, 'MEZAM', 'MEZAM', 'DELEGATION DEPARTEMENTALE DE LA MEZAM', 'MEZAM DIVISIONAL DELEGATION', 7),
(39, 'MOMO', 'MOMO', 'DELEGATION DEPARTEMENTALE DE LA MOMO', 'MOMO DIVISIONAL DELEGATION', 7),
(40, 'NGO-KETUNJIA', 'NGO-KETUNJIA', 'DELEGATION DEPARTEMENTALE DU NGO-KETUNJIA', 'NGO-KETUNJIA DIVISIONAL DELEGATION', 7),
(41, 'BAMBOUTOS', 'BAMBOUTOS', 'DELEGATION DEPARTEMENTALE DES BAMBOUTOS', 'BAMBOUTOS DIVISIONAL DELEGATION', 8),
(42, 'HAUT-NKAM', 'HAUT-NKAM', 'DELEGATION DEPARTEMENTALE DU HAUT-NKAM', 'HAUT-NKAM DIVISIONAL DELEGATION', 8),
(43, 'HAUTS-PLATEAUX', 'HAUTS-PLATEAUX', 'DELEGATION DEPARTEMENTALE DES HAUTS-PLATEAUX', 'HAUTS-PLATEAUX DIVISIONAL DELEGATION', 8),
(44, 'KOUNG-KHI', 'KOUNG-KHI', 'DELEGATION DEPARTEMENTALE DU KOUNG-KHI', 'KOUNG-KHI DIVISIONAL DELEGATION', 8),
(45, 'MENOUA', 'MENOUA', 'DELEGATION DEPARTEMENTALE DE LA MENOUA', 'MENOUA DIVISIONAL DELEGATION', 8),
(46, 'MIFI', 'MIFI', 'DELEGATION DEPARTEMENTALE DE LA MIFI', 'MIFI DIVISIONAL DELEGATION', 8),
(47, 'NDE', 'NDE', 'DELEGATION DEPARTEMENTALE DU NDE', 'NDE DIVISIONAL DELEGATION', 8),
(48, 'NOUN', 'NOUN', 'DELEGATION DEPARTEMENTALE DU NOUN', 'NOUN DIVISIONAL DELEGATION', 8),
(49, 'DJA-ET-LOBO', 'DJA-AND-LOBO', 'DELEGATION DEPARTEMENTALE DU DJA-ET-LOBO', 'DJA-AND-LOBO DIVISIONAL DELEGATION', 9),
(50, 'MVILA', 'MVILA', 'DELEGATION DEPARTEMENTALE DE LA MVILA', 'MVILA DIVISIONAL DELEGATION', 9),
(51, 'OCEAN', 'OCEAN', 'DELEGATION DEPARTEMENTALE L\'OCEAN', 'OCEAN DIVISIONAL DELEGATION', 9),
(52, 'VALLEE-DU-NTEM', 'VALLEE-OF-NTEM', 'DELEGATION DEPARTEMENTALE DE LA VALLEE-DU-NTEM', 'VALLEE-OF-NTEM DIVISIONAL DELEGATION', 9),
(53, 'FAKO', 'FAKO', 'DELEGATION DEPARTEMENTALE DU FAKO', 'FAKO DIVISIONAL DELEGATION', 10),
(54, 'KOUPE-MANENGOUBA', 'KOUPE-MANENGOUBA', 'DELEGATION DEPARTEMENTALE DU KOUPE-MANENGOUBA', 'KOUPE-MANENGOUBA DIVISIONAL DELEGATION', 10),
(55, 'LEBIALEM', 'LEBIALEM', 'DELEGATION DEPARTEMENTALE DU LEBIALEM', 'LEBIALEM DIVISIONAL DELEGATION', 10),
(56, 'MANYU', 'MANYU', 'DELEGATION DEPARTEMENTALE DE LA MANYU', 'MANYU DIVISIONAL DELEGATION', 10),
(57, 'MEME', 'MEME', 'DELEGATION DEPARTEMENTALE DE LA MEME', 'MEME DIVISIONAL DELEGATION', 10),
(58, 'NDIAN', 'NDIAN', 'DELEGATION DEPARTEMENTALE DU NDIAN', 'NDIAN DIVISIONAL DELEGATION', 10);

-- --------------------------------------------------------


